version: "3.4"
services:
  mqtt_broker:
    image: eclipse-mosquitto:1.6.7
    ports:
      - 1883:1883
      - 9001:9001

  mongodb:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  wifi-client-mock:
    build:
      context: src
      target: final-stage
    volumes:
      - ./src:/app
    command: ["python","runners/wifi_payload_client_runner.py"]
    depends_on:
      - mqtt_broker

  analyzer:
    build:
      context: src
      target: final-stage
    volumes:
      - ./src:/app
    command: ["python","runners/analyzer_runner.py"]
    depends_on:
      - mongodb

  databroker:
    build:
      context: src
      target: final-stage
    volumes:
      - ./src:/app
    command: ["python","runners/databroker_runner.py"]
    depends_on:
      - mqtt_broker
      - mongodb

  visual-backend:
    build:
      context: src
      target: final-stage
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
    command: ["python","datavisual/simple-backend.py"]
    depends_on:
      - mongodb
